# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22da18681799c1056b8ea5de41d46b962de0f62b316d0bff724c9f9301e6d5404e2477b8632b91113f918d2d78354f4d7864419fd678ccee12fd29b2f1295892

test:
  secret_key_base: 174767bb888b832b2b1f12fcf80fc30177da43db655f156f5d89e30a5e078b903f310b81d208a9f42dc466d1a76a18fb99f321890953507bb7c883fec36c9328

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
